image: python:3.6-alpine
before_script:
  - virtualenv --clear --never-download -p python3 .
  - ./bin/pip install -U pip setuptools
  - ./bin/pip install -e '.[test]'
stages:
  - tests

pytest:
  stage: tests
  script:
    - ./bin/pytest -v --cov=ocds_client/

flake8 check:
  stage: tests
  script:
    - ./bin/flake8 ocds_client/
