language: python
python:
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
    - .eggs
install:
  - pip install -r requirements.txt
  - pip install -e .[test]
script:
  - pytest --cov
after_success:
  - coveralls
sudo: false